facebook/WebDriverAgent

- WebDriverAgentLib/WebDriverCommands/FBDebugCommands.m
> add /session/sessionId/source endpoint

- WebDriverAgentLib/WebDriverCommands/FBElementCommands.m
Before, click wouldn't do anything
> Fix /click endpoint

- WebDriverAgentLib/FBWebServer.m
I created this a while back, but forgot to wire it up 😣
Adds some additional error info on the startup path.
> Use Helper method to allocate port

- WebDriverAgentLib/Routing/FBElementCache.m
Element Caching is unimplemented and will always return a new index, regardless of the same element being fetched.
This PR uses `-[UIElement uiaxElement]` as a unique value. `NSMapTable` weaking on the `UIAXElements` is used to ensure that the elements can be released when they are deallocated elsewhere.
> Implement Element Caching

- .travis.yml
- build.sh
Add a Script and configuration to get (at least builds) working on travis.
> Add Travis Config

- .travis.yml
Pretty sure this is why [we have issues with libxml on CI](https://travis-ci.org/facebook/WebDriverAgent/builds/85506536#L1581)
> Update Cocoapods Version for Travis

- WebDriverAgentLib/FBWebServer.m
- WebDriverAgentLib/Utilities/FBWDAConstants.h
- WebDriverAgentLib/Utilities/FBWDAConstants.m
Extracts out the port range to a global constant.
> Extract binding port range to constant

- WebDriverAgent.xcodeproj/project.pbxproj
- WebDriverAgentLib/FBWebDriverAgent.m
- WebDriverAgentLib/FBWebServer.m
- WebDriverAgentLib/Routing/FBRouteRequest.m
- WebDriverAgentLib/Utilities/FBWDAConstants.h
- WebDriverAgentLib/Utilities/FBWDAConstants.m
- WebDriverAgentLib/Utilities/FBWDALogger.h
- WebDriverAgentLib/Utilities/FBWDALogger.m
- WebDriverAgentLib/WebDriverCommands/FBAlertViewCommands.m
- WebDriverAgentLib/WebDriverCommands/FBCapabilitiesCommands.m
- WebDriverAgentLib/WebDriverCommands/FBFindElementCommands.m
Adds a Global logger object that can be controlled by an Environment Variable. Log all HTTP transactions verbosely if this is set.
> Verbose logging

- WebDriverAgentLib/FBWebServer.m
> log a message when the server starts

- WebDriverAgentLib/WebDriverCommands/FBElementCommands.m
> fix /value endpoint

- WebDriverAgentCore/Routing/FBElement.h
- WebDriverAgentLib/Categories/UIAElement+WebDriverAttributes.m
- XCTWebDriverAgentLib/Categories/XCUIElement+WebDriverAttributes.m
- XCTWebDriverAgentLib/Commands/FBElementCommands.m
submitting this PR in favor of #52
> /element/location

- XCTWebDriverAgentLib/Categories/XCUIElement+UIAClassMapping.h
- XCTWebDriverAgentLib/Categories/XCUIElement+UIAClassMapping.m
- XCTWebDriverAgentLib/Commands/FBFindElementCommands.m
> Handling UIACollectionCell  & UIATableCell  as one common type UIACellView

- PrivateHeaders/XCTest/XCEventGenerator.h
- WebDriverAgent.xcodeproj/project.pbxproj
- XCTWebDriverAgentLib/Categories/XCElementSnapshot+Helpers.m
- XCTWebDriverAgentLib/Categories/XCEventGenerator+SyncEvents.h
- XCTWebDriverAgentLib/Categories/XCEventGenerator+SyncEvents.m
- XCTWebDriverAgentLib/Commands/FBAlertViewCommands.m
Calling [XCUICoordinate tap] have some side effect which looks like additional tap on the screen. Switching to XCEventGenerator which is used by -[XCUIElement tap]
> Fixed alert accept & dismiss commands. 

- XCTWebDriverAgentLib/Categories/XCElementSnapshot+Helpers.h
- XCTWebDriverAgentLib/Categories/XCElementSnapshot+Helpers.m
- XCTWebDriverAgentLib/Categories/XCEventGenerator+SyncEvents.h
- XCTWebDriverAgentLib/Categories/XCUIElement+FBScrolling.m
It seems that "scrolview" property doesn't alwasy work for XCElementSnapshot so	we have	to travers view	hierarchy by hand
> Fixed scrollToVisible command

- Podfile
> Added inhibit_all_warnings! to Podfile

- Podfile
- WebDriverAgent.xcodeproj/project.pbxproj
- WebDriverAgentLibTests/FBWebDriverViewHierarchyMock.m
Resolves https://github.com/facebook/WebDriverAgent/issues/17
> Fixed UIAWebDriverAgent tests

- WebDriverAgentLib/WebDriverCommands/FBFindElementCommands.m
- XCTWebDriverAgentLib/Commands/FBFindElementCommands.m
Resolves:
https://github.com/facebook/WebDriverAgent/issues/34
https://github.com/facebook/WebDriverAgent/issues/33
> Added "accessibility id" and "id" locator strategy

- WebDriverAgent.xcodeproj/project.pbxproj
- WebDriverAgentCore/Routing/FBWebServer.m
- WebDriverAgentCore/Utilities/FBRuntimeUtils.h
- WebDriverAgentCore/Utilities/FBRuntimeUtils.m
- WebDriverAgentCore/Utilities/UIDevice+Wifi_IP.h
- WebDriverAgentCore/Utilities/UIDevice+Wifi_IP.m
Refactored FBWebServer by moving getting wifi IP address and collecting <FBCommandHandler> classes to separate files/classes.
> Refactored FBWebServer for better readability

- WebDriverAgentLib/WebDriverCommands/FBCustomCommands.m
It happens since Xcode 7.1 and failure cases look like this:
- it will properly lock simulator
- it will properly unlock simulator
- then throw exception "-lock element not found", even tho everything is ok
This would ignore such cases.
> Fix for lock command failure

- XCTWebDriverAgentLib/Commands/FBElementCommands.m
This method scrolls the element into view then 
returns its location.
Reference: https://github.com/facebook/WebDriverAgent/issues/89
> Add support for JsonWireProtocol element/:id/location_in_view

- Podfile
- Podfile.lock
- WebDriverAgent/main.m
Reverts facebook/WebDriverAgent#99
> Revert "HACK: Redefine free() to fix bug in AXRuntime.framework"

- XCTWebDriverAgentLib/Commands/FBElementCommands.m
Reverts facebook/WebDriverAgent#95
> Revert "Add support for JsonWireProtocol element/:id/location_in_view"
